name: Build SONU JAAT APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev
        pip3 install --user --upgrade buildozer cython virtualenv sh

    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer android debug
      env:
        BUILDOZER_WARN_ON_ROOT: 0

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: SONU_JAAT_music_Tester_APK
        path: bin/*.apk
